# Generated by Django 4.2.4 on 2023-08-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('message', models.TextField(default=True)),
                ('answered_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True)),
                ('nickname', models.TextField(blank=True)),
                ('is_admin', models.BooleanField(default=True)),
                ('admin_answered', models.BooleanField(default=False)),
                ('telegram_id', models.IntegerField(default=0)),
            ],
        ),
    ]
