# Generated by Django 4.2.4 on 2023-08-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='answered_to',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
